apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gha-runner-scale-set
  namespace: gha-runner-scale-set
spec:
  interval: 5m
  url: https://github.com/hamanigor/gha-runner-scale-set-helm-chart.git
  ref:
    tag: 0.12.1
  secretRef:
    name: github-secret
  
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease 
metadata:
  name: gha-runner-scale-set
  namespace: gha-runner-scale-set
spec:
  interval: 1m
  chart:
    spec: 
      chart: gha-runner-scale-set
      sourceRef:
        kind: GitRepository
        name: gha-runner-scale-set
      interval: 1m 
  valuesFrom:
    - kind: ConfigMap 
      name: gha-runner-scale-set-values-base
  values: 
    controllerServiceAccount:
    name: gha-runner-scale-set-controller-sa
    namespace: gha-runner-scale-set-controller
