apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-runner-scale-set-values-base
  namespace: gha-runner-scale-set
data:
  values.yaml: |
    githubConfigUrl: "https://github.com/power-Igor/test-java-runner"
    githubConfigSecret: "gha-github-pat"

    runnerScaleSetName: "arc-java"
    minRunners: 1
    maxRunners: 2

    # Bind RBAC to the controller SA
    controllerServiceAccount:
      name: gha-runner-scale-set-controller-sa
      namespace: gha-runner-scale-set-controller

    # —— Kubernetes mode (no DinD) ——
    containerMode:
      type: kubernetes

    # REQUIRED in kubernetes mode (ephemeral PVC for work dir)
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 5Gi

    # Runner pod template (keep small requests; tolerate control-plane taint)
    template:
      spec:
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
        imagePullSecrets:
          - name: docker-hub-cred
        containers:
          - name: runner
            image: "docker.io/19901/runner-java:1.0.0"
            env:
              - name: RUNNER_LABELS
                value: "arc,java"
            resources:
              requests:
                cpu: "200m"
                memory: "256Mi"
              limits:
                cpu: "1"
                memory: "1Gi"