apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-runner-scale-set-values-base
  namespace: gha-runner-scale-set
data:
  values.yaml: |
    githubConfigUrl: "https://github.com/hamanigor"
    githubConfigSecret: "github-secret"

    runnerScaleSetName: "arc-java"
    minRunners: 0
    maxRunners: 10

    containerMode:
      type: dind

    template:
      spec:
        imagePullSecrets:
          - name: docker-hub-cred
        containers:
          - name: runner
            image: "docker.io/19901/runner-java:1.0.0"  
            env:
              - name: RUNNER_LABELS
                value: "arc,java"
            resources:
              requests:
                cpu: "1"
                memory: "2Gi"
              limits:
                cpu: "4"
                memory: "6Gi"
