apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-runner-scale-set-values-base
  namespace: gha-runner-scale-set
data:
  values.yaml: |
    githubConfigUrl: "https://github.com/power-Igor/test-java-runner"
    githubConfigSecret: "gha-github-pat"

    runnerScaleSetName: "arc-java"
    minRunners: 1
    maxRunners: 2

    controllerServiceAccount:
      name: gha-runner-scale-set-controller-sa
      namespace: gha-runner-scale-set-controller

    containerMode:
      type: dind

    template:
      spec:
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"   # older clusters
            operator: "Exists"
            effect: "NoSchedule"
        containers:
          - name: runner
            env:
              - name: RUNNER_LABELS
                value: "arc,java"
              - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
                value: "30"
            resources:
              requests:
                cpu: "200m"
                memory: "256Mi"
              limits:
                cpu: "1"
                memory: "1Gi"
