apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-runner-scale-set-values-base
  namespace: gha-runner-scale-set
data:
  values.yaml: |
    githubConfigUrl: "https://github.com/power-Igor/test-java-runner"
    githubConfigSecret: "gha-github-pat"

    runnerScaleSetName: "arc-java"
    minRunners: 1
    maxRunners: 2

    controllerServiceAccount:
      name: gha-runner-scale-set-controller-sa
      namespace: gha-runner-scale-set-controller

    # Enable Docker-in-Docker; chart injects dind + init + volumes automatically
    containerMode:
      type: dind

    # Only override the runner container here (do NOT add dind/init/volumes)
    template:
      spec:
        imagePullSecrets:
          - name: docker-hub-cred
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
        containers:
          - name: runner
            image: 19901/arc/runner-java:1.0.0  # must include /home/runner/run.sh & (optionally) JDK
            # command is already set by chart; omit unless you need to change it
            env:
              - name: DOCKER_HOST
                value: unix:///var/run/docker.sock
              - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
                value: "120"
              - name: RUNNER_LABELS
                value: "arc,java"
              # - name: ACTIONS_RUNNER_DEBUG
              #   value: "true"
            resources:
              requests:
                cpu: "200m"
                memory: "256Mi"
              limits:
                cpu: "1"
                memory: "1Gi"
