apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-runner-scale-set-values-base
  namespace: gha-runner-scale-set
data:
  values.yaml: |
    githubConfigUrl: "https://github.com/power-Igor/test-java-runner"
    githubConfigSecret: "gha-github-pat"

    runnerScaleSetName: "arc-java"
    minRunners: 1
    maxRunners: 3

    controllerServiceAccount:
      name: gha-runner-scale-set-controller-sa
      namespace: gha-runner-scale-set-controller

    # Let the chart inject DinD and its init/volumes
    containerMode:
      type: dind

    template:
      spec:
        imagePullSecrets:
          - name: docker-hub-cred
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"

        # Only override the runner container (image/env/resources)
        containers:
          - name: runner
            image: docker.io/19901/runner-java:1.0.1  # must include /home/runner/run.sh and (optionally) JDK
            env:
              - name: DOCKER_HOST
                value: unix:///var/run/docker.sock
              - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
                value: "120"
              - name: RUNNER_LABELS
                value: "arc,java"
            resources:
              requests:
                cpu: "200m"
                memory: "256Mi"
              limits:
                cpu: "1"
                memory: "1Gi"