apiVersion: v1
kind: ConfigMap
metadata:
  name: plantuml-values-base
  namespace: plantuml
data:
  values.yaml: |
    image:
      repository: docker.io/19901/plantuml
      tag: "1"
      pullPolicy: IfNotPresent 

    imagePullSecrets: 
      - name: docker-hub-cred 

    