apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-values-base
  namespace: renovate
data:
  values.yaml: |
    image:
      repository: docker.io/19901/renovate
      tag: "39.164.0"
      pullPolicy: IfNotPresent 

    imagePullSecrets: 
      - name: docker-hub-cred 
